server:
  port: 8443
spring:
  data:
    mongodb:
      uri: mongodb://root:1234@localhost:27017/check-bot
telegram:
  api-url: https://api.telegram.org/
  webhook-path:  https://de5b-195-47-194-78.eu.ngrok.io
  bot-token: 5534042504:AAER0t1IvZV-UTMTEdM_EPc5RVxN1kHpWjI
  bot-name: magicexistsplcheckstestbot
  
#  https://api.telegram.org/bot5534042504:AAER0t1IvZV-UTMTEdM_EPc5RVxN1kHpWjI/setWebhook?url=https://de5b-195-47-194-78.eu.ngrok.io